version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: app
    ports:
      - 8085:8085
      - ${PUSHER_APP_PORT}:6001
      - 9912:9912
    depends_on:
      - redis
      - mariadb

  acs:
    build:
      context: docker
      target: base
    working_dir: /app
    volumes:
    - ./:/app
    - ./docker/supervisor.conf:/etc/supervisor/conf.d/goacs.conf:ro
    ports:
      - 8085:8085
      - ${PUSHER_APP_PORT}:6001
      - 9912:9912
    restart: on-failure
    depends_on:
      - redis
      - mariadb

  redis:
    image: redis:latest
    ports:
    - 16379:6379
    restart: always


  mariadb:
    image: mariadb:10.4
    volumes:
      - goacs-database-volume:/var/lib/mysql
      - ./docker/database:/docker-entrypoint-initdb.d
      - ./docker/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - 3399:3306
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  node:
    image: node:14
    working_dir: /app
    volumes:
    - ./:/app
    command: bash -c "npm install && npm run prod"


volumes:
  goacs-database-volume:
    driver: local
